/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import View.Dashboard;
import View.Guru;
import View.Jurusan;
import View.Kelas;
import View.Siswa;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author rizan
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Kiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pn_Dashboard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pn_Jurusan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pn_Guru = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pn_Kelas = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pn_Siswa = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pn_About = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pn_Logout = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Kanan = new javax.swing.JPanel();
        Dasar = new javax.swing.JPanel();
        PanelUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Kiri.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Book Shelf.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ALUMNII");

        pn_Dashboard.setBackground(new java.awt.Color(51, 51, 255));
        pn_Dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_Dashboard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pn_Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_DashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_DashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_DashboardMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Dashboard.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Dashboard");

        javax.swing.GroupLayout pn_DashboardLayout = new javax.swing.GroupLayout(pn_Dashboard);
        pn_Dashboard.setLayout(pn_DashboardLayout);
        pn_DashboardLayout.setHorizontalGroup(
            pn_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_DashboardLayout.setVerticalGroup(
            pn_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_Jurusan.setBackground(new java.awt.Color(51, 51, 255));
        pn_Jurusan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_Jurusan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pn_Jurusan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_JurusanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_JurusanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_JurusanMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/List.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Jurusan");

        javax.swing.GroupLayout pn_JurusanLayout = new javax.swing.GroupLayout(pn_Jurusan);
        pn_Jurusan.setLayout(pn_JurusanLayout);
        pn_JurusanLayout.setHorizontalGroup(
            pn_JurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_JurusanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_JurusanLayout.setVerticalGroup(
            pn_JurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_JurusanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_JurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_Guru.setBackground(new java.awt.Color(51, 51, 255));
        pn_Guru.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_Guru.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pn_Guru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_GuruMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_GuruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_GuruMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Teachehr.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Guru");

        javax.swing.GroupLayout pn_GuruLayout = new javax.swing.GroupLayout(pn_Guru);
        pn_Guru.setLayout(pn_GuruLayout);
        pn_GuruLayout.setHorizontalGroup(
            pn_GuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_GuruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_GuruLayout.setVerticalGroup(
            pn_GuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_GuruLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_GuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_Kelas.setBackground(new java.awt.Color(51, 51, 255));
        pn_Kelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_Kelas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pn_Kelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_KelasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_KelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_KelasMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Class.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Kelas");

        javax.swing.GroupLayout pn_KelasLayout = new javax.swing.GroupLayout(pn_Kelas);
        pn_Kelas.setLayout(pn_KelasLayout);
        pn_KelasLayout.setHorizontalGroup(
            pn_KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_KelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_KelasLayout.setVerticalGroup(
            pn_KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_KelasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_Siswa.setBackground(new java.awt.Color(51, 51, 255));
        pn_Siswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_Siswa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pn_Siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_SiswaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_SiswaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_SiswaMouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Graduate.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Siswa");

        javax.swing.GroupLayout pn_SiswaLayout = new javax.swing.GroupLayout(pn_Siswa);
        pn_Siswa.setLayout(pn_SiswaLayout);
        pn_SiswaLayout.setHorizontalGroup(
            pn_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_SiswaLayout.setVerticalGroup(
            pn_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_SiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_About.setBackground(new java.awt.Color(51, 51, 255));
        pn_About.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_About.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pn_About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_AboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_AboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_AboutMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Info.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("About");

        javax.swing.GroupLayout pn_AboutLayout = new javax.swing.GroupLayout(pn_About);
        pn_About.setLayout(pn_AboutLayout);
        pn_AboutLayout.setHorizontalGroup(
            pn_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_AboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_AboutLayout.setVerticalGroup(
            pn_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_AboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_Logout.setBackground(new java.awt.Color(51, 51, 255));
        pn_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_Logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pn_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_LogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_LogoutMouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logout.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Logout");

        javax.swing.GroupLayout pn_LogoutLayout = new javax.swing.GroupLayout(pn_Logout);
        pn_Logout.setLayout(pn_LogoutLayout);
        pn_LogoutLayout.setHorizontalGroup(
            pn_LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_LogoutLayout.setVerticalGroup(
            pn_LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout KiriLayout = new javax.swing.GroupLayout(Kiri);
        Kiri.setLayout(KiriLayout);
        KiriLayout.setHorizontalGroup(
            KiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KiriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pn_Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_Jurusan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_Guru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_Kelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_Siswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_About, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        KiriLayout.setVerticalGroup(
            KiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(87, 87, 87)
                .addComponent(pn_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_Jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_Guru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_Kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_Siswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_About, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        getContentPane().add(Kiri, java.awt.BorderLayout.LINE_START);

        Kanan.setBackground(new java.awt.Color(0, 0, 0));
        Kanan.setLayout(new java.awt.BorderLayout());

        Dasar.setBackground(new java.awt.Color(102, 102, 102));

        PanelUtama.setBackground(new java.awt.Color(255, 255, 255));
        PanelUtama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout DasarLayout = new javax.swing.GroupLayout(Dasar);
        Dasar.setLayout(DasarLayout);
        DasarLayout.setHorizontalGroup(
            DasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DasarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        DasarLayout.setVerticalGroup(
            DasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DasarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Kanan.add(Dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(Kanan, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1366, 768));
    }// </editor-fold>//GEN-END:initComponents

    private void pn_DashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_DashboardMouseEntered
        pn_Dashboard.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_pn_DashboardMouseEntered

    private void pn_DashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_DashboardMouseExited
        pn_Dashboard.setBackground(new Color(51, 51, 255));
    }//GEN-LAST:event_pn_DashboardMouseExited

    private void pn_DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_DashboardMouseClicked
        PanelUtama.removeAll();
        PanelUtama.add(new Dashboard());
        PanelUtama.repaint();
        PanelUtama.revalidate();
    }//GEN-LAST:event_pn_DashboardMouseClicked

    private void pn_JurusanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_JurusanMouseClicked
        PanelUtama.removeAll();
        PanelUtama.add(new Jurusan());
        PanelUtama.repaint();
        PanelUtama.revalidate();
    }//GEN-LAST:event_pn_JurusanMouseClicked

    private void pn_JurusanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_JurusanMouseEntered
        pn_Jurusan.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_pn_JurusanMouseEntered

    private void pn_JurusanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_JurusanMouseExited
        pn_Jurusan.setBackground(new Color(51, 51, 255));
    }//GEN-LAST:event_pn_JurusanMouseExited

    private void pn_GuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_GuruMouseClicked
        PanelUtama.removeAll();
        PanelUtama.add(new Guru());
        PanelUtama.repaint();
        PanelUtama.revalidate();
    }//GEN-LAST:event_pn_GuruMouseClicked

    private void pn_GuruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_GuruMouseEntered
        pn_Guru.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_pn_GuruMouseEntered

    private void pn_GuruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_GuruMouseExited
        pn_Guru.setBackground(new Color(51, 51, 255));
    }//GEN-LAST:event_pn_GuruMouseExited

    private void pn_KelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_KelasMouseClicked
        PanelUtama.removeAll();
        PanelUtama.add(new Kelas());
        PanelUtama.repaint();
        PanelUtama.revalidate();
    }//GEN-LAST:event_pn_KelasMouseClicked

    private void pn_KelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_KelasMouseEntered
        pn_Kelas.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_pn_KelasMouseEntered

    private void pn_KelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_KelasMouseExited
        pn_Kelas.setBackground(new Color(51, 51, 255));
    }//GEN-LAST:event_pn_KelasMouseExited

    private void pn_SiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_SiswaMouseClicked
        PanelUtama.removeAll();
        PanelUtama.add(new Siswa());
        PanelUtama.repaint();
        PanelUtama.revalidate();
    }//GEN-LAST:event_pn_SiswaMouseClicked

    private void pn_SiswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_SiswaMouseEntered
        pn_Siswa.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_pn_SiswaMouseEntered

    private void pn_SiswaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_SiswaMouseExited
        pn_Siswa.setBackground(new Color(51, 51, 255));
    }//GEN-LAST:event_pn_SiswaMouseExited

    private void pn_AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_AboutMouseClicked
        UIManager.put("OptionPane.background", Color.LIGHT_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.BLACK);
        JOptionPane.showMessageDialog(this, "Software ini dibuat untuk kepentingan pembelajaran JAVA\n"
                + "pada mata kuliah Pemograman Lanjutan pada Prodi Sistem Informasi S2\n"
                + "Istitut Teknologi Mojosari", "Tentang Kami", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_pn_AboutMouseClicked

    private void pn_AboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_AboutMouseEntered
        pn_About.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_pn_AboutMouseEntered

    private void pn_AboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_AboutMouseExited
        pn_About.setBackground(new Color(51, 51, 255));
    }//GEN-LAST:event_pn_AboutMouseExited

    private void pn_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LogoutMouseClicked
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_pn_LogoutMouseClicked

    private void pn_LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LogoutMouseEntered
        pn_Logout.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_pn_LogoutMouseEntered

    private void pn_LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LogoutMouseExited
        pn_Logout.setBackground(new Color(51, 51, 255));
    }//GEN-LAST:event_pn_LogoutMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        PanelUtama.removeAll();
        PanelUtama.add(new Dashboard());
        PanelUtama.repaint();
        PanelUtama.revalidate();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dasar;
    private javax.swing.JPanel Kanan;
    private javax.swing.JPanel Kiri;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pn_About;
    private javax.swing.JPanel pn_Dashboard;
    private javax.swing.JPanel pn_Guru;
    private javax.swing.JPanel pn_Jurusan;
    private javax.swing.JPanel pn_Kelas;
    private javax.swing.JPanel pn_Logout;
    private javax.swing.JPanel pn_Siswa;
    // End of variables declaration//GEN-END:variables
}
